spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: ./db/changelog/db.changelog-master.xml
    enabled: true
  mvc:
    static-path-pattern=/resources/**: